### PR TITLE
Replace unwrap by a if let statement

### LINKED ISSUE #25: Bug: unwrap() in route Profile and ProfileHl
When going manually to an invalid URL we should display a message that says the profile doesn't exist and not crash the entire application

### PR DESCRIPTION
**Pull request by yozhgoor**
closes #25

### CODE REVIEW

File: src/page_not_found.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    }
+
+    fn view(&self) -> Html {
+        html! {
+            <Callout
+                class=classes!("page-not-found")
+                title={"Page not found"}
+                intent=Intent::Warning
+            >
+                <Text>{"This profile does not seem to exist"}</Text>
```
Comment (cecton) [inline src/page_not_found.rs:29]: You're mixing page and profile. Is it page not found or profile not found? You must decide

File: src/app.rs [hunk 2]
```diff
@@ -173,21 +174,31 @@ impl Component for App {
...
+                                            <Profile
+                                                candidate=candidate.candidate
+                                                highlighted_tech=highlighted_tech
+                                            />
+                                        }
+                                    } else {
+                                        html! {
+                                            <PageNotFound />
+                                        }
+                                    }
```
Comment (cecton) [inline src/app.rs:201]: This is terribly indented and wrapped.

`if let Some(...) =` should not be cut.

The inside of the match arm should be indented by 1.

File: src/app.rs [hunk 3]
```diff
@@ -173,21 +174,31 @@ impl Component for App {
...
+                                        html! {
+                                            <Profile
+                                                candidate=candidate.candidate
+                                            />
+                                        }
+                                    } else {
+                                        html! {
+                                            <PageNotFound />
+                                        }
+                                    }
```
Comment (cecton) [inline src/app.rs:188]: Bad indentation but the line wrapping is more correct

File: src/app.rs [hunk 4]
```diff
@@ -173,21 +174,33 @@ impl Component for App {
...
+                                    AppRoute::ProfileHl(slug, highlighted_tech) =>
+                                        if let Some(candidate) = candidates.get(&slug.as_str())
+                                    {
```
Comment (cecton) [inline src/app.rs:192]: the `if` cannot be more indented than the block

**Review by cecton — APPROVED** [review]
